import 'package:flutter/widgets.dart';
import '../../l10n/app_localizations.dart';

export '../../l10n/app_localizations.dart';

extension AppLocalizationsHelperExtension on AppLocalizations {
  String translate(String key, {Map<String, String>? args}) {
    final map = localeName.startsWith('en') ? _enTranslations : _frTranslations;
    String result = map[key] ?? key;

    if (args != null) {
      args.forEach((k, v) {
        result = result.replaceAll('{$k}', v);
      });
    }

    return result;
  }
}

extension AppLocalizationsExtension on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);

  String tr(String key, {Map<String, String>? args}) {
    return l10n.translate(key, args: args);
  }
}

const Map<String, String> _frTranslations = {
    // General
    'app_name': 'SmartClass',
    'loading': 'Chargement...',
    'error': 'Erreur',
    'success': 'Succès',
    'retry': 'Réessayer',
    'cancel': 'Annuler',
    'confirm': 'Confirmer',
    'save': 'Enregistrer',
    'delete': 'Supprimer',
    'edit': 'Modifier',
    'create': 'Créer',
    'search': 'Rechercher',
    'filter': 'Filtrer',
    'sort': 'Trier',
    'close': 'Fermer',
    'back': 'Retour',
    'next': 'Suivant',
    'previous': 'Précédent',
    'done': 'Terminé',
    'skip': 'Ignorer',
    'continue': 'Continuer',
    'continue_action': 'Continuer',
    'yes': 'Oui',
    'no': 'Non',
    'ok': 'OK',
    'no_data': 'Aucune donnée disponible',
    'empty_state': 'Aucun élément',
    'try_again': 'Réessayer',
    'something_went_wrong': 'Quelque chose s\'est mal passé',
    'connection_error': 'Erreur de connexion',
    'permission_denied': 'Permission refusée',
    'not_found': 'Non trouvé',
    
    // Auth
    'login': 'Connexion',
    'logout': 'Déconnexion',
    'register': 'Inscription',
    'email': 'Email',
    'password': 'Mot de passe',
    'confirm_password': 'Confirmer le mot de passe',
    'forgot_password': 'Mot de passe oublié ?',
    'reset_password': 'Réinitialiser le mot de passe',
    'remember_me': 'Se souvenir de moi',
    'login_with_google': 'Se connecter avec Google',
    'login_with_apple': 'Se connecter avec Apple',
    'or_continue_with': 'Ou continuer avec',
    'dont_have_account': 'Pas encore de compte ?',
    'already_have_account': 'Déjà un compte ?',
    'sign_up': 'S\'inscrire',
    'sign_in': 'Se connecter',
    'welcome_back': 'Bon retour',
    'create_account': 'Créer un compte',
    'enter_email': 'Entrez votre email',
    'enter_password': 'Entrez votre mot de passe',
    'invalid_email': 'Email invalide',
    'password_too_short': 'Le mot de passe doit contenir au moins 8 caractères',
    'passwords_dont_match': 'Les mots de passe ne correspondent pas',
    'login_failed': 'Échec de la connexion',
    'registration_failed': 'Échec de l\'inscription',
    'email_already_exists': 'Cet email est déjà utilisé',
    'invalid_credentials': 'Identifiants invalides',
    'welcome_title': 'Bienvenue sur SmartClass',
    'welcome_subtitle': 'Accédez à votre espace d\'apprentissage intelligent',
    'email_label': 'Adresse e-mail',
    'email_hint': 'nom@exemple.edu',
    'password_hint': '••••••••',
    'login_button': 'Se connecter',
    'signup_button': 'S\'inscrire',
    'full_name_label': 'Nom complet',
    'full_name_hint': 'ex. Thomas Laurent',
    'required_badge': 'Requis',
    'academic_format_hint': 'Format académique recommandé',
    'password_rule': 'Au moins 8 car., 1 chiffre',
    'accept_terms_prefix': 'J\'accepte les',
    'and': 'et la',
    'or_signup_with': 'ou s\'inscrire avec',
    'login_with_microsoft': 'Se connecter avec Microsoft',
    'signup_with_microsoft': 'S\'inscrire avec Microsoft',
    'brand_badge_edtech': 'EdTech',
    'brand_badge_ai': 'AI Assisted',
    'step_2_profile': 'Étape 2 · Profil',
    'step_3_final': 'Étape 3 · Finalisation',
    'who_are_you': 'Qui êtes-vous ?',
    'role_intro': 'Choisissez votre profil pour personnaliser vos espaces d\'apprentissage et vos outils IA.',
    'recommended': 'Recommandé',
    'role_student_desc': 'Accédez à vos cours interactifs, devoirs assistés par IA, quiz et suivez votre progression en temps réel.',
    'role_teacher_desc': 'Gérez vos promotions, concevez des modules dynamiques et générez des évaluations automatisées.',
    'role_admin_desc': 'Supervisez l\'ensemble de votre établissement, orchestrez les accès et pilotez les métriques globales.',
    'tag_homework': 'Devoirs',
    'tag_ai_tutor': 'Tuteur IA',
    'tag_corrections': 'Corrigés',
    'tag_classes': 'Classes',
    'tag_dashboard': 'Tableau de bord',
    'tag_security': 'Sécurité',
    'trust_rgpd': 'Configuration sécurisée conforme aux standards académiques et protection RGPD renforcée.',
    'change_role_later': 'Vous pourrez changer de rôle ultérieurement dans les paramètres de votre compte.',
    'profile_setup_title': 'Configurez votre profil',
    'profile_setup_subtitle': 'Personnalisez vos informations académiques pour adapter les recommandations de vos cours et tuteurs IA.',
    'avatar_optional': 'Ajouter une photo de profil (Optionnel)',
    'institution_label': 'Établissement / Université',
    'level_label': 'Niveau d\'études / Spécialité',
    'interests_label': 'Centres d\'intérêt',
    'interests_hint': 'Sélectionnez au moins 3 matières pour nourrir votre Tuteur IA',
    'selected_count': '{count} sélectionnés',
    'other_interest': 'Autre intérêt',
    'validate_profile': 'Valider mon profil',
    'profile_edit_later': 'Vous pourrez modifier ces informations à tout moment dans vos Réglages.',
    'forgot_title': 'Mot de passe oublié ?',
    'forgot_subtitle': 'Saisissez votre adresse email académique pour recevoir un code d\'authentification à 4 chiffres.',
    'security_recovery': 'Sécurité & Récupération',
    'institutional_email': 'Adresse e-mail institutionnelle',
    'verified': 'Vérifiée',
    'pending_badge': 'En attente',
    'resend_email': 'Renvoyer l\'e-mail',
    'otp_title': 'Code de vérification',
    'otp_hint': 'Entrez le code temporaire envoyé à',
    'expires_in': 'Expire dans :',
    'resend_code': 'Renvoyer le code',
    'verify_code': 'Vérifier le code',
    'security_guaranteed_title': 'Sécurité académique garantie',
    'security_guaranteed_desc': 'Vos identifiants et clés de chiffrement sont protégés selon le protocole universitaire RGPD & SSO.',
    'back_to_login': 'Retour à la connexion',
    'email_not_verified': 'Veuillez vérifier votre email avant de vous connecter.',
    'account_locked': 'Compte temporairement verrouillé. Réessayez plus tard.',
    'too_many_requests': 'Trop de requêtes. Réessayez dans un instant.',
    'invalid_code': 'Code invalide ou expiré.',
    'verification_sent': 'Un nouveau code a été envoyé par email.',
    'reset_email_sent': 'Si un compte existe, un code de réinitialisation a été envoyé.',
    'logged_out': 'Déconnexion réussie.',
    'server_status': 'État du serveur',
    'server_online': 'En ligne',
    'server_offline': 'Hors ligne',
    'server_db_latency': 'BDD : {ms} ms',
    'server_checking': 'Vérification...',

    // Email verification (OTP)
    'verify_email_title': 'Vérification de l\'email',
    'verify_email_subtitle': 'Code de confirmation transmis à l\'adresse sécurisée',
    'otp_waiting_digit': 'En attente de saisie du {n}ème chiffre',
    'otp_complete': 'Code complet, prêt à vérifier',
    'nothing_received': 'Vous n\'avez rien reçu ?',
    'receive_sms': 'Recevoir par SMS sécurisé',
    'verify_continue': 'Vérifier et continuer',
    'ssl_footer': 'Chiffrement SSL 256-bit • Sécurité académique SmartClass',
    'countdown_available': 'Disponible',

    // Reset password
    'reset_password_header': 'Reset Password',
    'new_password_title': 'Nouveau mot de passe',
    'new_password_subtitle': 'Choisissez un mot de passe fort d\'au moins 8 caractères pour sécuriser votre compte SmartClass.',
    'new_password_label': 'Nouveau mot de passe',
    'security_level': 'Niveau de sécurité',
    'strength_weak': 'Faible',
    'strength_medium': 'Moyen',
    'strength_strong': 'Fort',
    'strength_very_strong': 'Très fort',
    'rule_min_length': 'Au moins 8 caractères',
    'rule_digit': 'Au moins un chiffre',
    'rule_uppercase': 'Au moins une majuscule',
    'rule_special': 'Au moins un caractère spécial (!@#\$)',
    'passwords_match': 'Identiques',
    'academic_advice_title': 'Conseil académique',
    'academic_advice_desc': 'Évitez d\'utiliser votre date de naissance ou votre identifiant d\'étudiant pour vos identifiants universitaires.',
    'updating': 'Mise à jour...',
    'password_updated': 'Mot de passe actualisé !',
    'e2e_footer': 'Chiffrement de bout en bout • Protection du compte SmartClass',
    'need_help': 'Besoin d\'aide ? Contacter le support universitaire',
    
    // Roles
    'role_teacher': 'Enseignant',
    'role_student': 'Étudiant',
    'role_admin': 'Administrateur',
    'select_role': 'Sélectionnez votre rôle',
    'teacher_description': 'Créer des cours, gérer des classes, évaluer les étudiants',
    'student_description': 'Accéder aux cours, participer aux examens, collaborer',
    'admin_description': 'Gérer la plateforme, superviser les utilisateurs',
    
    // Navigation
    'home': 'Accueil',
    'courses': 'Cours',
    'groups': 'Groupes',
    'exams': 'Examens',
    'videoconference': 'Visioconférence',
    'collaboration': 'Collaboration',
    'ai_assistant': 'Assistant IA',
    'community': 'Communauté',
    'profile': 'Profil',
    'settings': 'Paramètres',
    'notifications': 'Notifications',
    'calendar': 'Calendrier',
    'messages': 'Messages',
    'nav_my_courses': 'Mes Cours',
    
    // Courses
    'my_courses': 'Mes cours',
    'create_course': 'Créer un cours',
    'edit_course': 'Modifier le cours',
    'course_title': 'Titre du cours',
    'course_description': 'Description',
    'course_content': 'Contenu du cours',
    'import_pdf': 'Importer un PDF',
    'generate_with_ai': 'Générer avec l\'IA',
    'publish_course': 'Publier le cours',
    'draft': 'Brouillon',
    'published': 'Publié',
    'archived': 'Archivé',
    'course_created': 'Cours créé avec succès',
    'course_updated': 'Cours mis à jour',
    'course_deleted': 'Cours supprimé',
    'delete_course_confirm': 'Êtes-vous sûr de vouloir supprimer ce cours ?',
    'course_details': 'Détails du cours',
    'course_progress': 'Progression',
    'lessons': 'Leçons',
    'resources': 'Ressources',
    'no_courses': 'Aucun cours disponible',
    'join_course': 'Rejoindre un cours',
    'leave_course': 'Quitter le cours',
    
    // Groups
    'my_groups': 'Mes groupes',
    'create_group': 'Créer un groupe',
    'group_name': 'Nom du groupe',
    'group_code': 'Code d\'invitation',
    'join_group': 'Rejoindre un groupe',
    'leave_group': 'Quitter le groupe',
    'group_members': 'Membres du groupe',
    'invite_students': 'Inviter des étudiants',
    'remove_student': 'Retirer l\'étudiant',
    'group_created': 'Groupe créé',
    'group_updated': 'Groupe mis à jour',
    'invalid_group_code': 'Code de groupe invalide',
    'join_group_success': 'Vous avez rejoint le groupe',
    'no_groups': 'Aucun groupe',
    'manage_groups': 'Gérer les groupes',
    'teacher': 'Enseignant',
    'students': 'Étudiants',
    'pending_invitations': 'Invitations en attente',
    'accept_invitation': 'Accepter',
    'decline_invitation': 'Refuser',
    
    // Exams
    'my_exams': 'Mes examens',
    'create_exam': 'Créer un examen',
    'exam_title': 'Titre de l\'examen',
    'exam_duration': 'Durée',
    'exam_date': 'Date de l\'examen',
    'select_chapters': 'Sélectionner les chapitres',
    'generate_exam': 'Générer l\'examen',
    'start_exam': 'Commencer l\'examen',
    'submit_exam': 'Soumettre l\'examen',
    'exam_results': 'Résultats de l\'examen',
    'exam_completed': 'Examen terminé',
    'exam_in_progress': 'Examen en cours',
    'exam_not_started': 'Examen non commencé',
    'time_remaining': 'Temps restant',
    'anti_fraude_active': 'Mode anti-fraude activé',
    'fullscreen_required': 'Plein écran requis',
    'focus_lock_active': 'Verrouillage du focus actif',
    'copy_paste_blocked': 'Copier-coller bloqué',
    'exam_submitted': 'Examen soumis avec succès',
    'score': 'Score',
    'passed': 'Réussi',
    'failed': 'Échoué',
    'review_answers': 'Revoir les réponses',
    'correct_answer': 'Bonne réponse',
    'incorrect_answer': 'Mauvaise réponse',
    'no_exams': 'Aucun examen disponible',
    'simulation_exam': 'Simulation d\'examen',
    'official_exam': 'Examen officiel',
    'practice_mode': 'Mode entraînement',
    
    // Videoconference
    'live_sessions': 'Sessions en direct',
    'scheduled_sessions': 'Sessions programmées',
    'past_sessions': 'Sessions passées',
    'start_session': 'Démarrer la session',
    'join_session': 'Rejoindre la session',
    'session_title': 'Titre de la session',
    'session_description': 'Description',
    'session_date': 'Date',
    'session_duration': 'Durée',
    'recording': 'Enregistrement',
    'recording_started': 'Enregistrement démarré',
    'recording_stopped': 'Enregistrement arrêté',
    'replay_available': 'Replay disponible',
    'summary': 'Résumé',
    'transcription': 'Transcription',
    'participants': 'Participants',
    'host': 'Hôte',
    'no_sessions': 'Aucune session',
    'session_ended': 'Session terminée',
    'waiting_for_host': 'En attente de l\'hôte',
    'microphone': 'Microphone',
    'camera': 'Caméra',
    'screen_share': 'Partage d\'écran',
    'chat': 'Discussion',
    'raise_hand': 'Lever la main',
    
    // Collaboration
    'shared_resources': 'Ressources partagées',
    'share_resource': 'Partager une ressource',
    'my_shares': 'Mes partages',
    'resource_title': 'Titre de la ressource',
    'resource_type': 'Type de ressource',
    'resource_file': 'Fichier',
    'resource_link': 'Lien',
    'study_sessions': 'Sessions d\'étude',
    'create_study_session': 'Créer une session d\'étude',
    'session_topic': 'Sujet',
    'session_date_time': 'Date et heure',
    'comments': 'Commentaires',
    'add_comment': 'Ajouter un commentaire',
    'no_resources': 'Aucune ressource partagée',
    'no_study_sessions': 'Aucune session d\'étude',
    'join_study_session': 'Rejoindre la session',
    'resource_shared': 'Ressource partagée',
    'session_created': 'Session créée',
    
    // AI Assistant
    'ask_ai': 'Poser une question à l\'IA',
    'ai_tutor': 'Tuteur IA',
    'ai_generating': 'L\'IA génère...',
    'ai_response': 'Réponse de l\'IA',
    'generate_test': 'Générer un test',
    'generate_course': 'Générer un cours',
    'reformulate': 'Reformuler',
    'summarize': 'Résumer',
    'explain': 'Expliquer',
    'give_examples': 'Donner des exemples',
    'step_by_step': 'Pas à pas',
    'ai_context': 'Contexte : ce cours uniquement',
    'private_conversation': 'Conversation privée',
    'no_ai_history': 'Aucune conversation',
    'clear_history': 'Effacer l\'historique',
    'ai_error': 'Erreur de l\'IA, réessayez plus tard',

    // Student dashboard
    'student_greeting': 'Bonjour {name}',
    'student_greeting_default': 'Bonjour Salma',
    'student_degree_info': 'Licence 3 Informatique · Semestre 1',
    'active_streak': 'Série active',
    'streak_consecutive_days': '{count} jours consécutifs',
    'weekly_goal': 'Objectif hebdo',
    'goal_reached': '{pct}% atteint',
    'live_imminent': 'LIVE IMMINENT',
    'in_minutes': 'Dans {min} min',
    'join_live': 'Rejoindre le Live',
    'studio_ia_title': 'Studio IA · Révisions & Quiz',
    'studio_ia_desc': 'Génère un résumé de cours instantané ou crée un quiz d\'entraînement sur-mesure.',
    'course_summary': 'Résumé de cours',
    'course_summary_desc': 'Fiches & synthèse intelligente',
    'generate_action': 'Générer ✨',
    'practice_quiz': 'Quiz d\'entraînement',
    'practice_quiz_desc': 'Questions sur-mesure & QCM',
    'create_action': 'Créer ⚡',
    'enrolled_count': '({count} inscrits)',
    'student_course_progress': 'Progression du cours',
    'up_to_date': 'À jour',
    'in_progress': 'En cours',
    'upcoming_homework': 'Prochains Devoirs',
    'pending_count': '{count} en attente',
    'history': 'Historique',
    'questions_count': '{count} questions',
    'est_time': '~{min} min',
    'today_time': 'Aujourd\'hui, {time}',
    'tomorrow_time': 'Demain, {time}',
    'starts_action': 'Commencer',
    'deposit_action': 'Déposer',
    'cc_grade_weight': 'Comptant pour {pct}% de la note CC',
    'auto_ai_validation': 'Validation automatique par l\'IA activée',
    'git_or_file_desc': 'Dépôt Git ou fichier .py',
    'online_scheduled': 'Prévu en ligne',
    'view_all': 'Voir tout',
    'last_lesson': 'Dernière leçon',
    'next_step': 'Prochaine étape',

    // Teacher dashboard
    'greeting_hello': 'Bonjour,',
    'teacher_badge': 'Enseignant',
    'next_live': 'Prochain direct · {time}',
    'stat_students': 'Étudiants',
    'stat_active_courses': 'Cours Actifs',
    'stat_to_grade': 'À corriger',
    'stat_this_week': '+8 sem.',
    'stat_semester_2': 'Semestre 2',
    'stat_urgent': 'Urgent',
    'ai_banner_kicker': 'Assistant Pédagogique IA',
    'ai_banner_title': 'Créer un cours avec l\'IA',
    'ai_banner_desc': 'Générez un plan de cours interactif, des quiz et exercices en quelques secondes.',
    'generate_now': 'Générer maintenant',
    'my_classes': 'Mes Classes',
    'view_all_count': 'Voir tout ({count})',
    'completion_rate': 'Taux de complétion',
    'access_class': 'Accéder à la classe',
    'homework_count': 'Devoirs ({count})',

    // AI course creator
    'course_editor': 'Course Editor',
    'ai_engine_banner': 'Moteur Pédagogique IA v3.2',
    'ai_create_title': 'Créer un cours assisté par IA',
    'ai_create_desc': 'Fournissez vos supports de cours ou décrivez vos objectifs. L\'IA structure le plan, les leçons, les quiz et les exercices interactifs.',
    'smart_designer': 'Concepteur intelligent',
    'smart_designer_desc': 'Structurez vos unités d\'enseignement conformément aux normes LMD et référentiels européens.',
    'drop_pdf_title': 'Glisser un PDF/Document source ici',
    'drop_pdf_formats': 'Formats acceptés : PDF, Word (.docx), PPTX ou Markdown (max 50 Mo)',
    'browse_files': 'Parcourir les fichiers',
    'or_divider': 'OU',
    'topic_label': 'Sujet ou consignes spécifiques',
    'topic_hint': 'Ou décrivez le sujet du cours... Ex: \'Introduction aux bases de données relationnelles et requêtes SQL avancées pour Licence 3 Informatique avec 4 chapitres et exercices corrigés\'',
    'module_suggestions': 'Suggestions de modules',
    'chip_detailed_plan': 'Plan détaillé',
    'chip_quiz': 'Quiz interactif inclus',
    'chip_exercises': 'Exercices pratiques',
    'chip_cases': 'Études de cas',
    'subject_label': 'Matière académique',
    'academic_level_label': 'Niveau académique',
    'ai_params': 'Paramètres d\'alignement IA',
    'opt_quiz_title': 'Générer un quiz d\'évaluation automatique',
    'opt_quiz_desc': 'Intègre 10 QCM d\'assimilation avec barème et corrigés commentés',
    'opt_tone_title': 'Adapter le ton pédagogique universitaire',
    'opt_tone_desc': 'Vocabulaire soutenu, rigueur méthodologique et contextualisations',
    'generate_course_full': 'Générer le cours complet',
    'generating_course': 'Structuration IA en cours...',
    'course_generated': 'Cours généré avec succès !',
    'estimate_rgpd': 'Estimation : ~20 secondes • Modèle certifié RGPD Pédagogie Sup',

    // Profile
    'my_profile': 'Mon profil',
    'edit_profile': 'Modifier le profil',
    'first_name': 'Prénom',
    'last_name': 'Nom',
    'date_of_birth': 'Date de naissance',
    'phone': 'Téléphone',
    'address': 'Adresse',
    'bio': 'Bio',
    'avatar': 'Photo de profil',
    'change_avatar': 'Changer la photo',
    'profile_updated': 'Profil mis à jour',
    'account_settings': 'Paramètres du compte',
    'change_password': 'Changer le mot de passe',
    'current_password': 'Mot de passe actuel',
    'new_password': 'Nouveau mot de passe',
    'password_changed': 'Mot de passe modifié',
    'delete_account': 'Supprimer le compte',
    'delete_account_confirm': 'Cette action est irréversible. Êtes-vous sûr ?',
    
    // Settings
    'appearance': 'Apparence',
    'language': 'Langue',
    'font_size': 'Taille du texte',
    'font_family': 'Police',
    'theme_mode': 'Mode de thème',
    'light_mode': 'Mode clair',
    'dark_mode': 'Mode sombre',
    'system_mode': 'Système',
    'notifications_settings': 'Notifications',
    'push_notifications': 'Notifications push',
    'email_notifications': 'Notifications email',
    'data_privacy': 'Données et confidentialité',
    'export_data': 'Exporter mes données',
    'clear_cache': 'Vider le cache',
    'about': 'À propos',
    'version': 'Version',
    'terms_of_service': 'Conditions d\'utilisation',
    'privacy_policy': 'Politique de confidentialité',
    'open_source_licenses': 'Licences open source',
    'send_feedback': 'Envoyer un retour',
    'rate_app': 'Noter l\'application',
    'small': 'Petit',
    'medium': 'Moyen',
    'large': 'Grand',
    'extra_large': 'Très grand',
    'font_size_changed': 'Taille de police modifiée',
    'language_changed': 'Langue modifiée',
    'theme_changed': 'Thème modifié',
    'settings_saved': 'Paramètres enregistrés',
    
    // Errors & Empty States
    'no_internet': 'Pas de connexion internet',
    'check_connection': 'Vérifiez votre connexion',
    'server_error': 'Erreur du serveur',
    'unauthorized': 'Non autorisé',
    'session_expired': 'Session expirée',
    'please_login_again': 'Veuillez vous reconnecter',
    'feature_coming_soon': 'Fonctionnalité à venir',
    'under_development': 'En développement',
    
    // Validation
    'required_field': 'Ce champ est obligatoire',
    'invalid_format': 'Format invalide',
    'min_length': 'Minimum {count} caractères',
    'max_length': 'Maximum {count} caractères',
    'invalid_number': 'Nombre invalide',
    'invalid_date': 'Date invalide',
    'future_date_required': 'La date doit être dans le futur',
    'past_date_required': 'La date doit être dans le passé',

    // AI Assistant (Revision & Quiz)
    'ai_revision_title': 'Générer Mes Révisions',
    'ai_revision_header': 'Assistant de Révision IA',
    'ai_model_l3_badge': 'Modèle L3 Optimisé ✨',
    'ai_revision_subtitle': 'Transformez instantanément vos supports universitaires en synthèses dynamiques et cartes mémorielles.',
    'ai_source_step_title': 'Source du cours',
    'ai_ent_presynced': 'Pré-synchronisé ENT',
    'ai_select_module': 'SÉLECTIONNER UN MODULE',
    'ai_select_module_modal_title': 'Sélectionner votre module',
    'ai_import_doc_title': 'Importer un PDF / Doc personnel',
    'ai_import_doc_subtitle': 'Glissez votre cours ou TD (PDF, DOCX, TXT max 25 Mo)',
    'ai_import_doc_ready': 'Document prêt pour la synthèse sémantique',
    'ai_import_doc_success': 'Document universitaire importé avec succès !',
    'ai_format_step_title': 'Format souhaité',
    'ai_active_selection': 'Sélection active',
    'ai_format_step_subtitle': 'Choisissez la structure d\'assimilation cognitive la plus adaptée à vos révisions.',
    'ai_format_express': 'Résumé express',
    'ai_format_express_badge': '⏱️ Lecture 3 min',
    'ai_format_express_desc': 'Synthèse dense avec points-clés et théorèmes majeurs.',
    'ai_format_flashcards': 'Fiches mémo (Flashcards)',
    'ai_format_flashcards_badge': '🗂️ 15 cartes',
    'ai_format_flashcards_desc': 'Répétition espacée idéale pour mémoriser les formules.',
    'ai_format_mindmap': 'Carte mentale',
    'ai_format_mindmap_badge': '🧠 Arborescence',
    'ai_format_mindmap_desc': 'Vision panoramique et interdépendances logiques.',
    'ai_granularity_step_title': 'Niveau de détail',
    'ai_granularity_concise': 'Concis',
    'ai_granularity_balanced': 'Équilibré',
    'ai_granularity_detailed': 'Détaillé',
    'ai_granularity_desc_concise': 'Focus ultra-rapide : définitions directes, axiomes vitaux et aide-mémoire condensé pour les 10 dernières minutes avant l\'examen.',
    'ai_granularity_desc_balanced': 'Inclusions automatiques : théorèmes majeurs, extraits de code syntaxiques et calculs de complexité asymptotique O(n).',
    'ai_granularity_desc_detailed': 'Exhaustivité académique : démonstrations complètes pas à pas, variantes d\'exercices d\'annales et cas limites d\'implémentation.',
    'ai_generate_summary_btn': 'Générer le résumé via IA ✨',
    'ai_generating_analysis': 'Analyse sémantique en cours...',
    'ai_generate_subtext': 'Génération moyenne en 15 secondes • 100% aligné sur le programme',
    'ai_recent_summaries_title': 'Mes derniers résumés',
    'ai_see_all_count': 'Voir tout ({count})',
    'ai_share_link_copied': 'Lien de partage copié dans le presse-papiers !',
    'ai_summary_modal_title': 'Synthèse générée via IA ✨',
    'ai_export_pdf': 'Exporter PDF',
    'ai_practice_action': 'S\'entraîner',
    'ai_quiz_title': 'S\'Entraîner Avec L\'IA',
    'ai_quiz_generator_badge': 'Générateur de Quiz IA',
    'ai_quiz_subtitle': 'Générez un test sur mesure pour évaluer et consolider vos connaissances académiques.',
    'ai_change': 'Changer',
    'ai_select_course_title': 'Sélectionner la matière à entraîner',
    'ai_chapters_selection': 'Sélection des chapitres',
    'ai_chapters_selected_count': '({count} sélectionnés)',
    'select_all': 'Tout sélectionner',
    'deselect_all': 'Tout désélectionner',
    'ai_all_module': 'Tout le module',
    'ai_difficulty_level': 'Niveau de difficulté',
    'ai_adapted_exams': 'Adapté aux partiels S1',
    'ai_diff_beginner': 'Débutant',
    'ai_diff_beginner_sub': 'Notions socles',
    'ai_diff_intermediate': 'Intermédiaire',
    'ai_diff_intermediate_sub': 'Pièges & cas type',
    'ai_diff_expert': 'Expert',
    'ai_diff_expert_sub': 'Démonstrations',
    'ai_question_count_title': 'Nombre de questions',
    'ai_question_count_subtitle': 'Personnalisez la profondeur',
    'ai_questions_badge': '{count} questions',
    'ai_5_express': '5 (Express)',
    'ai_15_standard': '15 (Standard)',
    'ai_30_intensive': '30 (Intensif)',
    'ai_duration_estimate': 'Durée estimée : ~{min} minutes • ~1.2 min par question',
    'ai_evaluation_modalities': 'Modalités d\'évaluation',
    'ai_detailed_explanations': 'Explications détaillées',
    'ai_detailed_exp_sub': 'L\'IA analyse vos erreurs et affiche la méthodologie immédiatement après chaque réponse.',
    'ai_restitution_format': 'Format de restitution',
    'ai_timed_mode': 'Mode Chronométré',
    'ai_mcq_tf': 'QCM & Vrai/Faux',
    'ai_reassurance_badge': 'Propulsé par le modèle SmartClass L3 • Formulé à partir des annales et objectifs du syllabus officiel 2024.',
    'ai_start_quiz_btn': 'Créer et Démarrer le Quiz',
    'ai_generating_quiz': 'Génération du quiz académique...',
    'ai_quiz_subtext': 'Progression synchronisée • Historique disponible dans votre profil',
    'ai_question_counter': 'Question {current} / {total}',
    'ai_next_question': 'Question suivante',
    'ai_quit_test': 'Quitter l\'épreuve',
    'ai_explanation_prefix': 'Explication IA : ',
    'or': 'Ou',
    'open': 'Ouvrir',
    'share': 'Partager',
    'upcoming': 'À venir',
    'completed': 'Terminé',
    'level': 'Niveau d\'études',
    'all': 'Tous',
    'drafts': 'Brouillons',
  };
  
const Map<String, String> _enTranslations = {
    // General
    'app_name': 'SmartClass',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'retry': 'Retry',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'create': 'Create',
    'search': 'Search',
    'filter': 'Filter',
    'sort': 'Sort',
    'close': 'Close',
    'back': 'Back',
    'next': 'Next',
    'previous': 'Previous',
    'done': 'Done',
    'skip': 'Skip',
    'continue': 'Continue',
    'continue_action': 'Continue',
    'yes': 'Yes',
    'no': 'No',
    'ok': 'OK',
    'no_data': 'No data available',
    'empty_state': 'No items',
    'try_again': 'Try again',
    'something_went_wrong': 'Something went wrong',
    'connection_error': 'Connection error',
    'permission_denied': 'Permission denied',
    'not_found': 'Not found',
    
    // Auth
    'login': 'Login',
    'logout': 'Logout',
    'register': 'Register',
    'email': 'Email',
    'password': 'Password',
    'confirm_password': 'Confirm password',
    'forgot_password': 'Forgot password?',
    'reset_password': 'Reset password',
    'remember_me': 'Remember me',
    'login_with_google': 'Sign in with Google',
    'login_with_apple': 'Sign in with Apple',
    'or_continue_with': 'Or continue with',
    'dont_have_account': 'Don\'t have an account?',
    'already_have_account': 'Already have an account?',
    'sign_up': 'Sign up',
    'sign_in': 'Sign in',
    'welcome_back': 'Welcome back',
    'create_account': 'Create account',
    'enter_email': 'Enter your email',
    'enter_password': 'Enter your password',
    'invalid_email': 'Invalid email',
    'password_too_short': 'Password must be at least 8 characters',
    'passwords_dont_match': 'Passwords do not match',
    'login_failed': 'Login failed',
    'registration_failed': 'Registration failed',
    'email_already_exists': 'This email is already in use',
    'invalid_credentials': 'Invalid credentials',
    'welcome_title': 'Welcome to SmartClass',
    'welcome_subtitle': 'Access your intelligent learning space',
    'email_label': 'Email address',
    'email_hint': 'name@example.edu',
    'password_hint': '••••••••',
    'login_button': 'Sign in',
    'signup_button': 'Sign up',
    'full_name_label': 'Full name',
    'full_name_hint': 'e.g. Thomas Laurent',
    'required_badge': 'Required',
    'academic_format_hint': 'Academic format recommended',
    'password_rule': 'At least 8 chars, 1 digit',
    'accept_terms_prefix': 'I accept the',
    'and': 'and',
    'or_signup_with': 'or sign up with',
    'login_with_microsoft': 'Sign in with Microsoft',
    'signup_with_microsoft': 'Sign up with Microsoft',
    'brand_badge_edtech': 'EdTech',
    'brand_badge_ai': 'AI Assisted',
    'step_2_profile': 'Step 2 · Profile',
    'step_3_final': 'Step 3 · Finalization',
    'who_are_you': 'Who are you?',
    'role_intro': 'Choose your profile to personalize your learning spaces and AI tools.',
    'recommended': 'Recommended',
    'role_student_desc': 'Access your interactive courses, AI-assisted homework, quizzes and track your progress in real time.',
    'role_teacher_desc': 'Manage your cohorts, design dynamic modules and generate automated assessments.',
    'role_admin_desc': 'Supervise your entire institution, orchestrate access and steer global metrics.',
    'tag_homework': 'Homework',
    'tag_ai_tutor': 'AI Tutor',
    'tag_corrections': 'Corrections',
    'tag_classes': 'Classes',
    'tag_dashboard': 'Dashboard',
    'tag_security': 'Security',
    'trust_rgpd': 'Secure setup compliant with academic standards and reinforced GDPR protection.',
    'change_role_later': 'You can change your role later in your account settings.',
    'profile_setup_title': 'Set up your profile',
    'profile_setup_subtitle': 'Customize your academic information to tailor your course and AI tutor recommendations.',
    'avatar_optional': 'Add a profile picture (Optional)',
    'institution_label': 'Institution / University',
    'level_label': 'Study level / Major',
    'interests_label': 'Interests',
    'interests_hint': 'Select at least 3 subjects to feed your AI Tutor',
    'selected_count': '{count} selected',
    'other_interest': 'Other interest',
    'validate_profile': 'Validate my profile',
    'profile_edit_later': 'You can edit this information at any time in your Settings.',
    'forgot_title': 'Forgot password?',
    'forgot_subtitle': 'Enter your academic email address to receive a 4-digit authentication code.',
    'security_recovery': 'Security & Recovery',
    'institutional_email': 'Institutional email address',
    'verified': 'Verified',
    'pending_badge': 'Pending',
    'resend_email': 'Resend email',
    'otp_title': 'Verification code',
    'otp_hint': 'Enter the temporary code sent to',
    'expires_in': 'Expires in:',
    'resend_code': 'Resend code',
    'verify_code': 'Verify code',
    'security_guaranteed_title': 'Guaranteed academic security',
    'security_guaranteed_desc': 'Your credentials and encryption keys are protected under the university GDPR & SSO protocol.',
    'back_to_login': 'Back to login',
    'email_not_verified': 'Please verify your email before logging in.',
    'account_locked': 'Account temporarily locked. Please try again later.',
    'too_many_requests': 'Too many requests. Please try again shortly.',
    'invalid_code': 'Invalid or expired code.',
    'verification_sent': 'A new code was sent to your email.',
    'reset_email_sent': 'If an account exists, a reset code was sent.',
    'logged_out': 'Logged out successfully.',
    'server_status': 'Server status',
    'server_online': 'Online',
    'server_offline': 'Offline',
    'server_db_latency': 'DB: {ms} ms',
    'server_checking': 'Checking...',

    // Email verification (OTP)
    'verify_email_title': 'Email verification',
    'verify_email_subtitle': 'Confirmation code sent to the secure address',
    'otp_waiting_digit': 'Waiting for digit no. {n}',
    'otp_complete': 'Complete code, ready to verify',
    'nothing_received': 'Didn\'t receive anything?',
    'receive_sms': 'Receive via secure SMS',
    'verify_continue': 'Verify and continue',
    'ssl_footer': '256-bit SSL encryption • SmartClass academic security',
    'countdown_available': 'Available',

    // Reset password
    'reset_password_header': 'Reset Password',
    'new_password_title': 'New password',
    'new_password_subtitle': 'Choose a strong password of at least 8 characters to secure your SmartClass account.',
    'new_password_label': 'New password',
    'security_level': 'Security level',
    'strength_weak': 'Weak',
    'strength_medium': 'Medium',
    'strength_strong': 'Strong',
    'strength_very_strong': 'Very strong',
    'rule_min_length': 'At least 8 characters',
    'rule_digit': 'At least one digit',
    'rule_uppercase': 'At least one uppercase letter',
    'rule_special': 'At least one special character (!@#\$)',
    'passwords_match': 'Matching',
    'academic_advice_title': 'Academic tip',
    'academic_advice_desc': 'Avoid using your date of birth or student ID for your university credentials.',
    'updating': 'Updating...',
    'password_updated': 'Password updated!',
    'e2e_footer': 'End-to-end encryption • SmartClass account protection',
    'need_help': 'Need help? Contact university support',
    
    // Roles
    'role_teacher': 'Teacher',
    'role_student': 'Student',
    'role_admin': 'Administrator',
    'select_role': 'Select your role',
    'teacher_description': 'Create courses, manage classes, assess students',
    'student_description': 'Access courses, take exams, collaborate',
    'admin_description': 'Manage platform, supervise users',
    
    // Navigation
    'home': 'Home',
    'courses': 'Courses',
    'groups': 'Groups',
    'exams': 'Exams',
    'videoconference': 'Videoconference',
    'collaboration': 'Collaboration',
    'ai_assistant': 'AI Assistant',
    'community': 'Community',
    'profile': 'Profile',
    'settings': 'Settings',
    'notifications': 'Notifications',
    'calendar': 'Calendar',
    'messages': 'Messages',
    'nav_my_courses': 'My Courses',
    
    // Courses
    'my_courses': 'My courses',
    'create_course': 'Create a course',
    'edit_course': 'Edit course',
    'course_title': 'Course title',
    'course_description': 'Description',
    'course_content': 'Course content',
    'import_pdf': 'Import PDF',
    'generate_with_ai': 'Generate with AI',
    'publish_course': 'Publish course',
    'draft': 'Draft',
    'published': 'Published',
    'archived': 'Archived',
    'course_created': 'Course created successfully',
    'course_updated': 'Course updated',
    'course_deleted': 'Course deleted',
    'delete_course_confirm': 'Are you sure you want to delete this course?',
    'course_details': 'Course details',
    'course_progress': 'Progress',
    'lessons': 'Lessons',
    'resources': 'Resources',
    'no_courses': 'No courses available',
    'join_course': 'Join a course',
    'leave_course': 'Leave course',
    
    // Groups
    'my_groups': 'My groups',
    'create_group': 'Create a group',
    'group_name': 'Group name',
    'group_code': 'Invitation code',
    'join_group': 'Join a group',
    'leave_group': 'Leave group',
    'group_members': 'Group members',
    'invite_students': 'Invite students',
    'remove_student': 'Remove student',
    'group_created': 'Group created',
    'group_updated': 'Group updated',
    'invalid_group_code': 'Invalid group code',
    'join_group_success': 'You joined the group',
    'no_groups': 'No groups',
    'manage_groups': 'Manage groups',
    'teacher': 'Teacher',
    'students': 'Students',
    'pending_invitations': 'Pending invitations',
    'accept_invitation': 'Accept',
    'decline_invitation': 'Decline',
    
    // Exams
    'my_exams': 'My exams',
    'create_exam': 'Create an exam',
    'exam_title': 'Exam title',
    'exam_duration': 'Duration',
    'exam_date': 'Exam date',
    'select_chapters': 'Select chapters',
    'generate_exam': 'Generate exam',
    'start_exam': 'Start exam',
    'submit_exam': 'Submit exam',
    'exam_results': 'Exam results',
    'exam_completed': 'Exam completed',
    'exam_in_progress': 'Exam in progress',
    'exam_not_started': 'Exam not started',
    'time_remaining': 'Time remaining',
    'anti_fraude_active': 'Anti-cheat mode active',
    'fullscreen_required': 'Fullscreen required',
    'focus_lock_active': 'Focus lock active',
    'copy_paste_blocked': 'Copy-paste blocked',
    'exam_submitted': 'Exam submitted successfully',
    'score': 'Score',
    'passed': 'Passed',
    'failed': 'Failed',
    'review_answers': 'Review answers',
    'correct_answer': 'Correct answer',
    'incorrect_answer': 'Incorrect answer',
    'no_exams': 'No exams available',
    'simulation_exam': 'Simulation exam',
    'official_exam': 'Official exam',
    'practice_mode': 'Practice mode',
    
    // Videoconference
    'live_sessions': 'Live sessions',
    'scheduled_sessions': 'Scheduled sessions',
    'past_sessions': 'Past sessions',
    'start_session': 'Start session',
    'join_session': 'Join session',
    'session_title': 'Session title',
    'session_description': 'Description',
    'session_date': 'Date',
    'session_duration': 'Duration',
    'recording': 'Recording',
    'recording_started': 'Recording started',
    'recording_stopped': 'Recording stopped',
    'replay_available': 'Replay available',
    'summary': 'Summary',
    'transcription': 'Transcription',
    'participants': 'Participants',
    'host': 'Host',
    'no_sessions': 'No sessions',
    'session_ended': 'Session ended',
    'waiting_for_host': 'Waiting for host',
    'microphone': 'Microphone',
    'camera': 'Camera',
    'screen_share': 'Screen share',
    'chat': 'Chat',
    'raise_hand': 'Raise hand',
    
    // Collaboration
    'shared_resources': 'Shared resources',
    'share_resource': 'Share a resource',
    'my_shares': 'My shares',
    'resource_title': 'Resource title',
    'resource_type': 'Resource type',
    'resource_file': 'File',
    'resource_link': 'Link',
    'study_sessions': 'Study sessions',
    'create_study_session': 'Create study session',
    'session_topic': 'Topic',
    'session_date_time': 'Date and time',
    'comments': 'Comments',
    'add_comment': 'Add comment',
    'no_resources': 'No shared resources',
    'no_study_sessions': 'No study sessions',
    'join_study_session': 'Join session',
    'resource_shared': 'Resource shared',
    'session_created': 'Session created',
    
    // AI Assistant
    'ask_ai': 'Ask AI a question',
    'ai_tutor': 'AI Tutor',
    'ai_generating': 'AI is generating...',
    'ai_response': 'AI Response',
    'generate_test': 'Generate a test',
    'generate_course': 'Generate a course',
    'reformulate': 'Reformulate',
    'summarize': 'Summarize',
    'explain': 'Explain',
    'give_examples': 'Give examples',
    'step_by_step': 'Step by step',
    'ai_context': 'Context: this course only',
    'private_conversation': 'Private conversation',
    'no_ai_history': 'No conversation history',
    'clear_history': 'Clear history',
    'ai_error': 'AI error, please try again later',

    // Student dashboard
    'student_greeting': 'Hello {name}',
    'student_greeting_default': 'Hello Salma',
    'student_degree_info': 'Bachelor 3 in Computer Science · Semester 1',
    'active_streak': 'Active streak',
    'streak_consecutive_days': '{count} consecutive days',
    'weekly_goal': 'Weekly goal',
    'goal_reached': '{pct}% reached',
    'live_imminent': 'LIVE IMMINENT',
    'in_minutes': 'In {min} min',
    'join_live': 'Join Live',
    'studio_ia_title': 'AI Studio · Revision & Quiz',
    'studio_ia_desc': 'Generate an instant course summary or create a tailored practice quiz.',
    'course_summary': 'Course summary',
    'course_summary_desc': 'Smart flashcards & summary',
    'generate_action': 'Generate ✨',
    'practice_quiz': 'Practice quiz',
    'practice_quiz_desc': 'Tailored questions & MCQ',
    'create_action': 'Create ⚡',
    'enrolled_count': '({count} enrolled)',
    'student_course_progress': 'Course progress',
    'up_to_date': 'Up to date',
    'in_progress': 'In progress',
    'upcoming_homework': 'Upcoming Homework',
    'pending_count': '{count} pending',
    'history': 'History',
    'questions_count': '{count} questions',
    'est_time': '~{min} min',
    'today_time': 'Today, {time}',
    'tomorrow_time': 'Tomorrow, {time}',
    'starts_action': 'Start',
    'deposit_action': 'Submit',
    'cc_grade_weight': 'Counts for {pct}% of continuous assessment',
    'auto_ai_validation': 'Automated AI validation enabled',
    'git_or_file_desc': 'Git repository or .py file',
    'online_scheduled': 'Scheduled online',
    'view_all': 'See all',
    'last_lesson': 'Last lesson',
    'next_step': 'Next step',

    // Teacher dashboard
    'greeting_hello': 'Hello,',
    'teacher_badge': 'Teacher',
    'next_live': 'Next live · {time}',
    'stat_students': 'Students',
    'stat_active_courses': 'Active courses',
    'stat_to_grade': 'To grade',
    'stat_this_week': '+8 wk.',
    'stat_semester_2': 'Semester 2',
    'stat_urgent': 'Urgent',
    'ai_banner_kicker': 'AI Teaching Assistant',
    'ai_banner_title': 'Create a course with AI',
    'ai_banner_desc': 'Generate an interactive lesson plan, quizzes and exercises in seconds.',
    'generate_now': 'Generate now',
    'my_classes': 'My Classes',
    'view_all_count': 'See all ({count})',
    'completion_rate': 'Completion rate',
    'access_class': 'Open class',
    'homework_count': 'Homework ({count})',

    // AI course creator
    'course_editor': 'Course Editor',
    'ai_engine_banner': 'AI Teaching Engine v3.2',
    'ai_create_title': 'Create an AI-assisted course',
    'ai_create_desc': 'Provide your course materials or describe your goals. AI structures the outline, lessons, quizzes and interactive exercises.',
    'smart_designer': 'Smart designer',
    'smart_designer_desc': 'Structure your teaching units in line with LMD standards and European frameworks.',
    'drop_pdf_title': 'Drop a PDF/source document here',
    'drop_pdf_formats': 'Accepted formats: PDF, Word (.docx), PPTX or Markdown (max 50 MB)',
    'browse_files': 'Browse files',
    'or_divider': 'OR',
    'topic_label': 'Topic or specific instructions',
    'topic_hint': 'Or describe the course topic... E.g. \'Introduction to relational databases and advanced SQL queries for 3rd-year Computer Science with 4 chapters and corrected exercises\'',
    'module_suggestions': 'Module suggestions',
    'chip_detailed_plan': 'Detailed outline',
    'chip_quiz': 'Interactive quiz included',
    'chip_exercises': 'Practical exercises',
    'chip_cases': 'Case studies',
    'subject_label': 'Academic subject',
    'academic_level_label': 'Academic level',
    'ai_params': 'AI alignment settings',
    'opt_quiz_title': 'Generate an automatic assessment quiz',
    'opt_quiz_desc': 'Includes 10 assimilation MCQs with grading scheme and commented corrections',
    'opt_tone_title': 'Adapt the academic pedagogical tone',
    'opt_tone_desc': 'Formal vocabulary, methodological rigor and contextualization',
    'generate_course_full': 'Generate full course',
    'generating_course': 'AI structuring in progress...',
    'course_generated': 'Course generated successfully!',
    'estimate_rgpd': 'Estimate: ~20 seconds • GDPR-certified Higher-Ed model',

    // Profile
    'my_profile': 'My profile',
    'edit_profile': 'Edit profile',
    'first_name': 'First name',
    'last_name': 'Last name',
    'date_of_birth': 'Date of birth',
    'phone': 'Phone',
    'address': 'Address',
    'bio': 'Bio',
    'avatar': 'Profile picture',
    'change_avatar': 'Change picture',
    'profile_updated': 'Profile updated',
    'account_settings': 'Account settings',
    'change_password': 'Change password',
    'current_password': 'Current password',
    'new_password': 'New password',
    'password_changed': 'Password changed',
    'delete_account': 'Delete account',
    'delete_account_confirm': 'This action is irreversible. Are you sure?',
    
    // Settings
    'appearance': 'Appearance',
    'language': 'Language',
    'font_size': 'Font size',
    'font_family': 'Font family',
    'theme_mode': 'Theme mode',
    'light_mode': 'Light mode',
    'dark_mode': 'Dark mode',
    'system_mode': 'System',
    'notifications_settings': 'Notifications',
    'push_notifications': 'Push notifications',
    'email_notifications': 'Email notifications',
    'data_privacy': 'Data & privacy',
    'export_data': 'Export my data',
    'clear_cache': 'Clear cache',
    'about': 'About',
    'version': 'Version',
    'terms_of_service': 'Terms of service',
    'privacy_policy': 'Privacy policy',
    'open_source_licenses': 'Open source licenses',
    'send_feedback': 'Send feedback',
    'rate_app': 'Rate app',
    'small': 'Small',
    'medium': 'Medium',
    'large': 'Large',
    'extra_large': 'Extra large',
    'font_size_changed': 'Font size changed',
    'language_changed': 'Language changed',
    'theme_changed': 'Theme changed',
    'settings_saved': 'Settings saved',
    
    // Errors & Empty States
    'no_internet': 'No internet connection',
    'check_connection': 'Check your connection',
    'server_error': 'Server error',
    'unauthorized': 'Unauthorized',
    'session_expired': 'Session expired',
    'please_login_again': 'Please log in again',
    'feature_coming_soon': 'Feature coming soon',
    'under_development': 'Under development',
    
    // Validation
    'required_field': 'This field is required',
    'invalid_format': 'Invalid format',
    'min_length': 'Minimum {count} characters',
    'max_length': 'Maximum {count} characters',
    'invalid_number': 'Invalid number',
    'invalid_date': 'Invalid date',
    'future_date_required': 'Date must be in the future',
    'past_date_required': 'Date must be in the past',

    // AI Assistant (Revision & Quiz)
    'ai_revision_title': 'Generate My Revisions',
    'ai_revision_header': 'AI Revision Assistant',
    'ai_model_l3_badge': 'Optimized L3 Model ✨',
    'ai_revision_subtitle': 'Instantly turn university course materials into dynamic summaries and memory cards.',
    'ai_source_step_title': 'Course Source',
    'ai_ent_presynced': 'ENT Pre-synchronized',
    'ai_select_module': 'SELECT A MODULE',
    'ai_select_module_modal_title': 'Select your module',
    'ai_import_doc_title': 'Import a personal PDF / Doc',
    'ai_import_doc_subtitle': 'Drag your lecture notes or tutorial (PDF, DOCX, TXT max 25 MB)',
    'ai_import_doc_ready': 'Document ready for semantic synthesis',
    'ai_import_doc_success': 'University document imported successfully!',
    'ai_format_step_title': 'Desired Format',
    'ai_active_selection': 'Active selection',
    'ai_format_step_subtitle': 'Choose the cognitive learning structure best suited for your study session.',
    'ai_format_express': 'Express Summary',
    'ai_format_express_badge': '⏱️ 3 min read',
    'ai_format_express_desc': 'Dense synthesis highlighting key points and major theorems.',
    'ai_format_flashcards': 'Flashcards',
    'ai_format_flashcards_badge': '🗂️ 15 cards',
    'ai_format_flashcards_desc': 'Spaced repetition designed to memorize formulas.',
    'ai_format_mindmap': 'Mind Map',
    'ai_format_mindmap_badge': '🧠 Tree structure',
    'ai_format_mindmap_desc': 'Panoramic overview and logical dependencies.',
    'ai_granularity_step_title': 'Detail Level',
    'ai_granularity_concise': 'Concise',
    'ai_granularity_balanced': 'Balanced',
    'ai_granularity_detailed': 'Detailed',
    'ai_granularity_desc_concise': 'Ultra-fast focus: direct definitions, vital axioms, and condensed cheat-sheet for the last 10 minutes before an exam.',
    'ai_granularity_desc_balanced': 'Automatic inclusions: major theorems, code snippets, and asymptotic complexity calculations O(n).',
    'ai_granularity_desc_detailed': 'Academic comprehensiveness: step-by-step demonstrations, exam problem variants, and edge-case implementations.',
    'ai_generate_summary_btn': 'Generate summary with AI ✨',
    'ai_generating_analysis': 'Semantic analysis in progress...',
    'ai_generate_subtext': 'Average generation in 15 seconds • 100% curriculum aligned',
    'ai_recent_summaries_title': 'My Recent Summaries',
    'ai_see_all_count': 'See all ({count})',
    'ai_share_link_copied': 'Share link copied to clipboard!',
    'ai_summary_modal_title': 'AI Generated Summary ✨',
    'ai_export_pdf': 'Export PDF',
    'ai_practice_action': 'Practice',
    'ai_quiz_title': 'Practice with AI',
    'ai_quiz_generator_badge': 'AI Quiz Generator',
    'ai_quiz_subtitle': 'Generate a tailored test to assess and consolidate your academic knowledge.',
    'ai_change': 'Change',
    'ai_select_course_title': 'Select subject to practice',
    'ai_chapters_selection': 'Chapter Selection',
    'ai_chapters_selected_count': '({count} selected)',
    'select_all': 'Select all',
    'deselect_all': 'Deselect all',
    'ai_all_module': 'All module',
    'ai_difficulty_level': 'Difficulty Level',
    'ai_adapted_exams': 'Adapted for S1 exams',
    'ai_diff_beginner': 'Beginner',
    'ai_diff_beginner_sub': 'Core concepts',
    'ai_diff_intermediate': 'Intermediate',
    'ai_diff_intermediate_sub': 'Traps & standard cases',
    'ai_diff_expert': 'Expert',
    'ai_diff_expert_sub': 'Demonstrations',
    'ai_question_count_title': 'Number of questions',
    'ai_question_count_subtitle': 'Customize depth',
    'ai_questions_badge': '{count} questions',
    'ai_5_express': '5 (Express)',
    'ai_15_standard': '15 (Standard)',
    'ai_30_intensive': '30 (Intensive)',
    'ai_duration_estimate': 'Estimated duration: ~{min} minutes • ~1.2 min per question',
    'ai_evaluation_modalities': 'Assessment Modalities',
    'ai_detailed_explanations': 'Detailed Explanations',
    'ai_detailed_exp_sub': 'AI analyzes your errors and reveals methodology immediately after each answer.',
    'ai_restitution_format': 'Response Format',
    'ai_timed_mode': 'Timed Mode',
    'ai_mcq_tf': 'MCQ & True/False',
    'ai_reassurance_badge': 'Powered by SmartClass L3 model • Formulated from past exams and official 2024 syllabus objectives.',
    'ai_start_quiz_btn': 'Create and Start Quiz',
    'ai_generating_quiz': 'Generating academic quiz...',
    'ai_quiz_subtext': 'Synchronized progress • History available in your profile',
    'ai_question_counter': 'Question {current} / {total}',
    'ai_next_question': 'Next question',
    'ai_quit_test': 'Quit test',
    'ai_explanation_prefix': 'AI Explanation: ',
    'or': 'Or',
    'open': 'Open',
    'share': 'Share',
    'upcoming': 'Upcoming',
    'completed': 'Completed',
    'level': 'Study level',
    'all': 'All',
    'drafts': 'Drafts',
  };